<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;
use CodeIgniter\I18n\Time;

class KosSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'nama' => 'Kost Gang Rambutan',
                'jenis_promosi' => 'D.FREE',
                'daftar_promosi' => Time::now(),
                'pemilik' => 'Adi',
                'user_id' => 2,
                "wa" => '6282289331862',
                'harga'    => 500000,
                'deskripsi' => 'Kos yang berada di jalan Tirtayasa Gg Rambutan 8 Sukabumi Bandar Lampung',
                'tipe'    => 'Kos Wanita',
                'provinsi' => 'LAMPUNG',
                'kabupaten' => 'KOTA BANDAR LAMPUNG',
                'alamat' => 'Jl. Tirtayasa Gg Rambutan 8 Sukabumi Bandar Lampung',
                'kamar_mandi_dalam'    => true,
                'ac' => false,
                'wifi'    => false,
                'thumbnail' => 'Kost Gang Rambutan/rambutan1.jpg',
                'foto1' => 'Kost Gang Rambutan/rambutan2.jpg',
                'foto2' => 'Kost Gang Rambutan/rambutan3.jpg',
                'foto3' => 'Kost Gang Rambutan/rambutan4.jpg',
                'foto4' => 'Kost Gang Rambutan/rambutan5.jpg',
                'created_at' => Time::now(),
            ],
            [
                'nama' => 'DC Kost',
                'jenis_promosi' => 'D.FREE',
                'daftar_promosi' => Time::now(),
                'pemilik' => 'Ismail',
                'user_id' => 2,
                "wa" => '6282196012183',
                'harga'    => 1700000,
                'deskripsi' => 'Lokasi Strategis, Aman, Bersih, Bebas Banjir, Dekat Dengan Pusat Perbelanjaan',
                'tipe'    => 'Kos Campuran',
                'provinsi' => 'LAMPUNG',
                'kabupaten' => 'KOTA BANDAR LAMPUNG',
                'alamat' => 'Jl. Gatot Subroto No.29, Tj. Raya, Kec. Kedamaian, Kota Bandar Lampung, Lampung',
                'kamar_mandi_dalam'    => true,
                'ac' => true,
                'wifi'    => true,
                'thumbnail' => 'DC Kost/DC1.jpg',
                'foto1' => 'DC Kost/DC2.jpg',
                'foto2' => 'DC Kost/DC3.jpg',
                'foto3' => 'DC Kost/DC4.jpg',
                'foto4' => 'DC Kost/DC5.jpg',
                'created_at' => Time::now(),
            ],
            [
                'nama' => 'Kost Annisa',
                'jenis_promosi' => 'D.FREE',
                'daftar_promosi' => Time::now(),
                'pemilik' => 'Zehan Oktavia',
                'user_id' => 2,
                "wa" => '6282196012183',
                'harga'    => 1750000,
                'deskripsi' => 'Lokasi Strategis, Aman, Bersih, Bebas Banjir, Dekat Dengan Pusat Perbelanjaan',
                'tipe'    => 'Kos Campuran',
                'provinsi' => 'LAMPUNG',
                'kabupaten' => 'KOTA BANDAR LAMPUNG',
                'alamat' => 'Jl. Jaya, Way Halim Permai, Kec. Sukarame, Kota Bandar Lampung, Lampung',
                'kamar_mandi_dalam'    => true,
                'ac' => true,
                'wifi'    => true,
                'thumbnail' => 'Annisa Kost/Annisa1.jpg',
                'foto1' => 'Annisa Kost/Annisa1.jpg',
                'foto2' => 'Annisa Kost/Annisa3.jpg',
                'foto3' => 'Annisa Kost/Annisa4.jpg',
                'foto4' => 'Annisa Kost/Annisa5.jpg',
                'created_at' => Time::now(),
            ],
            [
                'nama' => 'Aza Kost Eksklusif',
                'jenis_promosi' => 'D.FREE',
                'daftar_promosi' => Time::now(),
                'pemilik' => 'Yulkaizar',
                'user_id' => 2,
                "wa" => '6282194741805',
                'harga'    => 1500000,
                'deskripsi' => 'Lokasi Strategis, Aman, Bersih, Bebas Banjir, Dekat Dengan Pusat Perbelanjaan, Memiliki parkiran luas dilengkapi CCTV, Smart TV, Meja, Kursi, Lemari Baju, dan Kulkas.',
                'tipe'    => 'Kos Campuran',
                'provinsi' => 'LAMPUNG',
                'kabupaten' => 'KOTA BANDAR LAMPUNG',
                'alamat' => 'Jl. Amir Hamzah 1 No.77/14, Gotong Royong, Kec. Tj. Karang Pusat, Kota Bandar Lampung, Lampung',
                'kamar_mandi_dalam'    => true,
                'ac' => true,
                'wifi'    => true,
                'thumbnail' => 'Aza Kost Eksklusif/aza1.jpg',
                'foto1' => 'Aza Kost Eksklusif/aza2.jpg',
                'foto2' => 'Aza Kost Eksklusif/aza3.jpg',
                'foto3' => 'Aza Kost Eksklusif/aza4.jpg',
                'foto4' => 'Aza Kost Eksklusif/aza5.jpg',
                'created_at' => Time::now(),
            ],
            [
                'nama' => 'Kost Antasari Flaminggo Residence',
                'jenis_promosi' => 'D.FREE',
                'daftar_promosi' => Time::now(),
                'pemilik' => 'Patra',
                'user_id' => 2,
                "wa" => '6287865256590',
                'harga'    => 1200000,
                'deskripsi' => 'Lokasi aman, bebas banjir, pagar keliling..',
                'tipe'    => 'Kos Campuran',
                'provinsi' => 'LAMPUNG',
                'kabupaten' => 'KOTA BANDAR LAMPUNG',
                'alamat' => 'Jl. Bintara I No.50, Sukarame, Kec. Sukarame, Kota Bandar Lampung, Lampung 35122',
                'kamar_mandi_dalam'    => true,
                'ac' => true,
                'wifi'    => true,
                'thumbnail' => 'Kost Antasari/anta1.jpg',
                'foto1' => 'Kost Antasari/anta2.jpg',
                'foto2' => 'Kost Antasari/anta3.jpg',
                'foto3' => 'Kost Antasari/anta4.jpg',
                'foto4' => 'Kost Antasari/anta5.jpg',
                'created_at' => Time::now(),
            ],
            [
                'nama' => 'Kost Bunda Heti',
                'jenis_promosi' => 'D.FREE',
                'daftar_promosi' => Time::now(),
                'pemilik' => 'Heti Wirianti',
                'user_id' => 2,
                "wa" => '6285369450728',
                'harga'    => 1100000,
                'deskripsi' => 'Lokasi aman, bebas banjir, pagar keliling..',
                'tipe'    => 'Kos Campuran',
                'provinsi' => 'LAMPUNG',
                'kabupaten' => 'KOTA BANDAR LAMPUNG',
                'alamat' => 'Gg. Mekar 3, Kemiling Permai, Kec. Kemiling, Kota Bandar Lampung, Lampung 35151',
                'kamar_mandi_dalam'    => true,
                'ac' => true,
                'wifi'    => true,
                'thumbnail' => 'Kost Bunda Heti/bun1.jpg',
                'foto1' => 'Kost Bunda Heti/bun2.jpg',
                'foto2' => 'Kost Bunda Heti/bun3.jpg',
                'foto3' => 'Kost Bunda Heti/bun4.jpg',
                'foto4' => 'Kost Bunda Heti/bun5.jpg',
                'created_at' => Time::now(),
            ],
            [
                'nama' => 'Kost Putri Stephannie Exclusive',
                'jenis_promosi' => 'D.FREE',
                'daftar_promosi' => Time::now(),
                'pemilik' => 'Novi',
                'user_id' => 2,
                "wa" => '6282194550906',
                'harga'    => 1500000,
                'deskripsi' => '',
                'tipe'    => 'Kos Putri',
                'provinsi' => 'LAMPUNG',
                'kabupaten' => 'KOTA BANDAR LAMPUNG',
                'alamat' => 'Jl. Way Abung No.4, Pahoman, Kec. Tlk. Betung Utara, Kota Bandar Lampung, Lampung',
                'kamar_mandi_dalam'    => true,
                'ac' => true,
                'wifi'    => true,
                'thumbnail' => 'Kost Putri Stephannie/step1.jpg',
                'foto1' => 'Kost Putri Stephannie/step2.jpg',
                'foto2' => 'Kost Putri Stephannie/step3.jpg',
                'foto3' => 'Kost Putri Stephannie/step4.jpg',
                'foto4' => 'Kost Putri Stephannie/step5.jpg',
                'created_at' => Time::now(),
            ],
            [
                'nama' => 'Kost Rihanz',
                'jenis_promosi' => 'D.FREE',
                'daftar_promosi' => Time::now(),
                'pemilik' => 'Surya',
                'user_id' => 2,
                "wa" => '6283165902428',
                'harga'    => 450000,
                'deskripsi' => '',
                'tipe'    => 'Kos Putra',
                'provinsi' => 'LAMPUNG',
                'kabupaten' => 'KOTA BANDAR LAMPUNG',
                'alamat' => 'Jl. Badak GG Swadaya no 25, Sidodadi',
                'kamar_mandi_dalam'    => false,
                'ac' => false,
                'wifi'    => true,
                'thumbnail' => 'Kost Rihanz/rih1.jpg',
                'foto1' => 'Kost Rihanz/rih2.jpg',
                'foto2' => 'Kost Rihanz/rih3.jpg',
                'foto3' => 'Kost Rihanz/rih4.jpg',
                'foto4' => 'Kost Rihanz/rih5.jpg',
                'created_at' => Time::now(),
            ],
        ];

        // Simple Queries
        // $this->db->query('INSERT INTO kos (nama, harga, deskripsi, tipe, alamat, kamar_mandi_dalam, ac, wifi, thumbnail, created_at) VALUES(:nama:, :harga:, :deskripsi:, :tipe:, :alamat:, :kamar_mandi_dalam:, :ac:, :wifi:, :thumbnail:, :created_at:)', $data);

        // Using Query Builder
        $this->db->table('kos')->insertBatch($data);
    }
}
